name = "Ultimate Worldgen"
author = "badooga"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07c38ca8d36d92f981635def060bb1bb596a368c549219312d4f7b928c1a6c54"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "config/openloader/data"
