name = "World Reborn"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1549f6c9c813d484b6a23ae3fda55c883dfaf28f669381901303b3cb8ea9887b"

[versions]
minecraft = "1.20.1"
quilt = "0.19.3-beta.1"

[options]
datapack-folder = "config/openloader/data"
