name = "Ultimate Worldgen"
author = "badooga"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf709c74668996d5e53ff8e4b2e90160f6ac95fbd85c21fcec30803a05cf44fd"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "config/openloader/data"
