name = "Ultimate Worldgen"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df95be2d03a6fc13a23b84389d912436d301cac78b9b4f18717d85f659563e0d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
datapack-folder = "config/openloader/data"
