name = "Ultimate Worldgen"
author = "badooga"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "128e6508082a4ca37dcb2df267acf0fc4c12924f7d70895decdd74857d7e1bef"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
datapack-folder = "config/openloader/data"
