name = "Ultimate Worldgen"
author = "badooga"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efaef795c5c78b7bd3d9fc3ab575bdc085b18f208122a380decbd69e574e2476"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "config/openloader/data"
